name: cs224G_techpack_ai
channels:
  - conda-forge  
  - defaults
dependencies:
  - python=3.10  
  - pip
  - matplotlib
  - pip:
      - torch
      - torchvision
      - openai
      - fastapi
      - flask
      - supabase
      - flask_cors
      - loguru
      - werkzeug
      - uvicorn
      - gspread
      - google-auth
      - google-auth-oauthlib
      - google-auth-httplib2
      - openpyxl
      - pandas
      - transformers
      - opencv-python
